// Hardcoded top models - Updated 2025-01-05
// These are curated for optimal story/video generation performance

export const TOP_TEXT_MODELS = {
  topQuality: [
    {
      id: 'anthropic/claude-4.5-haiku-20251001',
      name: 'Claude Haiku 4.5',
      provider: 'Anthropic',
      pricing: { prompt: 0.000001, completion: 0.000005 },
      contextLength: 200000,
      description: 'Fastest Claude, frontier-level performance',
    },
    {
      id: 'anthropic/claude-3.5-sonnet',
      name: 'Claude 3.5 Sonnet',
      provider: 'Anthropic',
      pricing: { prompt: 0.000003, completion: 0.000015 },
      contextLength: 200000,
      description: 'Top quality, best for story generation',
    },
    {
      id: 'openai/gpt-5',
      name: 'GPT-5',
      provider: 'OpenAI',
      pricing: { prompt: 0.00001, completion: 0.00001 },
      contextLength: 400000,
      description: 'OpenAI latest flagship model',
    },
    {
      id: 'google/gemini-2.5-pro-exp',
      name: 'Gemini 2.5 Pro Experimental',
      provider: 'Google',
      pricing: { prompt: 0, completion: 0 },
      contextLength: 2000000,
      description: 'Free, 2M ultra-long context',
    },
  ],
  bestValue: [
    {
      id: 'meta-llama/llama-3.3-70b-instruct',
      name: 'Llama 3.3 70B Instruct',
      provider: 'Meta',
      pricing: { prompt: 0.00000018, completion: 0.00000018 },
      contextLength: 131072,
      description: 'Best value, close to GPT-4 quality',
    },
    {
      id: 'google/gemini-flash-1.5-8b',
      name: 'Gemini 1.5 Flash 8B',
      provider: 'Google',
      pricing: { prompt: 0.0000000375, completion: 0.00000015 },
      contextLength: 1000000,
      description: 'Ultra-fast and cheap, 1M context',
    },
    {
      id: 'qwen/qwen-2.5-72b-instruct',
      name: 'Qwen 2.5 72B Instruct',
      provider: 'Alibaba',
      pricing: { prompt: 0.00000035, completion: 0.00000035 },
      contextLength: 131072,
      description: 'Chinese optimized, great value',
    },
    {
      id: 'deepseek/deepseek-chat',
      name: 'DeepSeek V3',
      provider: 'DeepSeek',
      pricing: { prompt: 0.00000014, completion: 0.00000028 },
      contextLength: 65536,
      description: 'Code and reasoning expert',
    },
  ],
  fastest: [
    {
      id: 'minimax/minimax-m2',
      name: 'MiniMax M2',
      provider: 'MiniMax',
      pricing: { prompt: 0.00000015, completion: 0.00000045 },
      contextLength: 196608,
      description: 'Ultra-fast inference, ideal for agents',    },
    {
      id: 'google/gemini-flash-2.0',
      name: 'Gemini 2.0 Flash',
      provider: 'Google',
      pricing: { prompt: 0.000000075, completion: 0.0000003 },
      contextLength: 1000000,
      description: 'Fastest Gemini model',
    },
    {
      id: 'openai/gpt-4o-mini',
      name: 'GPT-4o Mini',
      provider: 'OpenAI',
      pricing: { prompt: 0.00000015, completion: 0.0000006 },
      contextLength: 128000,
      description: 'Fast and affordable',
    },
  ],
  free: [
    {
      id: 'google/gemini-2.5-pro-exp:free',
      name: 'Gemini 2.5 Pro (Free)',
      provider: 'Google',
      pricing: { prompt: 0, completion: 0 },
      contextLength: 2000000,
      description: 'Completely free, top quality',
    },
    {
      id: 'meta-llama/llama-3.3-70b-instruct:free',
      name: 'Llama 3.3 70B (Free)',
      provider: 'Meta',
      pricing: { prompt: 0, completion: 0 },
      contextLength: 131072,
      description: 'Free and powerful',
    },
    {
      id: 'qwen/qwen-2.5-72b-instruct:free',
      name: 'Qwen 2.5 72B (Free)',
      provider: 'Alibaba',
      pricing: { prompt: 0, completion: 0 },
      contextLength: 131072,
      description: 'Free Chinese-optimized model',
    },
  ],
};

export const TOP_IMAGE_MODELS = [
  // Replicate official collection: https://replicate.com/collections/text-to-image
  // Sorted by usage count, data updated on 2025-01-05
  {
    id: 'black-forest-labs/flux-schnell',
    owner: 'black-forest-labs',
    name: 'FLUX Schnell',
    description: 'Fastest and cheapest, 534M runs',
    runs: 534300000,
    quality: 'Good',
    speed: 'Ultra-fast (1-2s)',
    cost: '$0.003/image',
  },
  {
    id: 'stability-ai/sdxl',
    owner: 'stability-ai',
    name: 'Stable Diffusion XL',
    description: 'Classic and stable, 82.6M runs',
    runs: 82600000,
    quality: 'Good',
    speed: 'Medium (5-7s)',
    cost: '$0.002/image',
  },
  {
    id: 'black-forest-labs/flux-1.1-pro',
    owner: 'black-forest-labs',
    name: 'FLUX 1.1 Pro',
    description: 'Latest fastest FLUX, 63.2M runs',
    runs: 63200000,
    quality: 'Highest',
    speed: 'Ultra-fast (2-3s)',
    cost: '$0.04/image',
  },
  {
    id: 'black-forest-labs/flux-kontext-pro',
    owner: 'black-forest-labs',
    name: 'FLUX Kontext Pro',
    description: 'Text editing expert, 32.4M runs',
    runs: 32400000,
    quality: 'Highest',
    speed: 'Fast (3-4s)',
    cost: '$0.05/image',
  },
  {
    id: 'google/nano-banana',
    owner: 'google',
    name: 'Nano Banana (Gemini 2.5)',
    description: 'Google latest image editing, 30.6M runs',
    runs: 30600000,
    quality: 'High',
    speed: 'Fast (2-3s)',
    cost: '$0.03/image',
  },
  {
    id: 'black-forest-labs/flux-dev',
    owner: 'black-forest-labs',
    name: 'FLUX Dev',
    description: '12B parameters, 30.4M runs',
    runs: 30400000,
    quality: 'High',
    speed: 'Medium (6-8s)',
    cost: '$0.025/image',
  },
  {
    id: 'tencent/hunyuan-image-3',
    owner: 'tencent',
    name: 'Hunyuan Image 3',
    description: 'Tencent Hunyuan, 17.7K runs',
    runs: 17700,
    quality: 'Excellent',
    speed: 'Medium',
    cost: '~$0.05/image',
  },
  {
    id: 'black-forest-labs/flux-pro',
    owner: 'black-forest-labs',
    name: 'FLUX Pro',
    description: 'Top quality, 13.5M runs',
    runs: 13500000,
    quality: 'Excellent',
    speed: 'Medium (5-6s)',
    cost: '$0.055/image',
  },
  {
    id: 'bytedance/seedream-4',
    owner: 'bytedance',
    name: 'Seedream 4',
    description: 'ByteDance 4K resolution, 7.5M runs',
    runs: 7500000,
    quality: 'Excellent',
    speed: 'Slow',
    cost: '~$0.08/image',
  },
  {
    id: 'comfyui/any-comfyui-workflow',
    owner: 'comfyui',
    name: 'ComfyUI Workflow',
    description: 'Run any ComfyUI workflow, 6.9M runs',
    runs: 6900000,
    quality: 'Customizable',
    speed: 'Variable',
    cost: 'Variable',
  },
  {
    id: 'recraft-ai/recraft-v3',
    owner: 'recraft-ai',
    name: 'Recraft V3',
    description: 'SOTA text rendering, 6.7M runs',
    runs: 6700000,
    quality: 'High',
    speed: 'Fast (3-4s)',
    cost: '$0.04/image',
  },
  {
    id: 'google/imagen-4',
    owner: 'google',
    name: 'Imagen 4',
    description: 'Google flagship, 5.3M runs',
    runs: 5300000,
    quality: 'Highest',
    speed: 'Medium',
    cost: '$0.05/image',
  },
  {
    id: 'ideogram-ai/ideogram-v3-turbo',
    owner: 'ideogram-ai',
    name: 'Ideogram V3 Turbo',
    description: 'Fastest cheapest V3, 3.8M runs',
    runs: 3800000,
    quality: 'High',
    speed: 'Ultra-fast (1-2s)',
    cost: '$0.04/image',
  },
  {
    id: 'bytedance/seedream-3',
    owner: 'bytedance',
    name: 'Seedream 3',
    description: '2K native HD, 2.8M runs',
    runs: 2800000,
    quality: 'Excellent',
    speed: 'Medium',
    cost: '~$0.06/image',
  },
  {
    id: 'ideogram-ai/ideogram-v2',
    owner: 'ideogram-ai',
    name: 'Ideogram V2',
    description: 'Text inpainting expert, 2.5M runs',
    runs: 2500000,
    quality: 'High',
    speed: 'Fast (3-5s)',
    cost: '$0.08/image',
  },
  {
    id: 'ideogram-ai/ideogram-v3-quality',
    owner: 'ideogram-ai',
    name: 'Ideogram V3 Quality',
    description: 'Highest quality V3, 1.9M runs',
    runs: 1900000,
    quality: 'Excellent',
    speed: 'Medium (4-6s)',
    cost: '$0.10/image',
  },
  {
    id: 'google/imagen-4-fast',
    owner: 'google',
    name: 'Imagen 4 Fast',
    description: 'Speed-optimized Imagen, 1.7M runs',
    runs: 1700000,
    quality: 'High',
    speed: 'Fast (2-3s)',
    cost: '$0.03/image',
  },
  {
    id: 'google/imagen-3',
    owner: 'google',
    name: 'Imagen 3',
    description: 'Detailed light and shadow aesthetics, 1.7M runs',
    runs: 1700000,
    quality: 'Excellent',
    speed: 'Medium',
    cost: '$0.045/image',
  },
  {
    id: 'stability-ai/stable-diffusion-3.5-large',
    owner: 'stability-ai',
    name: 'Stable Diffusion 3.5 Large',
    description: 'High-resolution artistic style, 1.7M runs',
    runs: 1700000,
    quality: 'High',
    speed: 'Medium',
    cost: '$0.04/image',
  },
  {
    id: 'google/imagen-4-ultra',
    owner: 'google',
    name: 'Imagen 4 Ultra',
    description: 'Quality-optimized Imagen, 994K runs',
    runs: 994200,
    quality: 'Ultimate',
    speed: 'Slow',
    cost: '$0.08/image',
  },
  {
    id: 'qwen/qwen-image',
    owner: 'qwen',
    name: 'Qwen Image',
    description: 'Text rendering expert, 869K runs',
    runs: 869000,
    quality: 'Excellent',
    speed: 'Fast',
    cost: '~$0.03/image',
  },
  {
    id: 'recraft-ai/recraft-v3-svg',
    owner: 'recraft-ai',
    name: 'Recraft V3 SVG',
    description: 'First SVG generation model, 306K runs',
    runs: 306500,
    quality: 'Vector graphics',
    speed: 'Fast',
    cost: '$0.05/image',
  },
  {
    id: 'luma/photon-flash',
    owner: 'luma',
    name: 'Photon Flash',
    description: 'Luma accelerated version, 180K runs',
    runs: 180000,
    quality: 'High',
    speed: 'Ultra-fast',
    cost: '$0.04/image',
  },
  {
    id: 'leonardoai/lucid-origin',
    owner: 'leonardoai',
    name: 'Lucid Origin',
    description: 'Artistic vision prompt following, 103K runs',
    runs: 103200,
    quality: 'Artistic',
    speed: 'Medium',
    cost: '~$0.06/image',
  },
  {
    id: 'bria/image-3.2',
    owner: 'bria',
    name: 'Bria Image 3.2',
    description: 'Commercial licensed data training, 61K runs',
    runs: 61000,
    quality: 'Commercial-grade',
    speed: 'Fast',
    cost: '~$0.05/image',
  },
  {
    id: 'bria/fibo',
    owner: 'bria',
    name: 'Bria FIBO',
    description: 'SOTA enterprise-grade open source, 697 runs',
    runs: 697,
    quality: 'Enterprise-grade',
    speed: 'Fast',
    cost: '~$0.05/image',
  },
];

export const TOP_VIDEO_MODELS = [
  // Replicate official collection: https://replicate.com/collections/image-to-video
  {
    id: 'kwaivgi/kling-v2.1',
    owner: 'kwaivgi',
    name: 'Kling v2.1',
    description: 'Kwai most popular video model',
    runs: 2500000,
    quality: 'Excellent',
    speed: 'Medium',
    cost: '~$0.10/video',
  },
  {
    id: 'bytedance/seedance-1-lite',
    owner: 'bytedance',
    name: 'Seedance 1 Lite',
    description: 'ByteDance fast version',
    runs: 1600000,
    quality: 'Good',
    speed: 'Fast',
    cost: '~$0.05/video',
  },
  {
    id: 'bytedance/seedance-1-pro',
    owner: 'bytedance',
    name: 'Seedance 1 Pro',
    description: 'ByteDance professional version',
    runs: 931200,
    quality: 'Excellent',
    speed: 'Medium',
    cost: '~$0.15/video',
  },
  {
    id: 'kwaivgi/kling-v2.5-turbo-pro',
    owner: 'kwaivgi',
    name: 'Kling v2.5 Turbo Pro',
    description: 'Kwai latest turbo version',
    runs: 639800,
    quality: 'Excellent',
    speed: 'Fast',
    cost: '~$0.12/video',
  },
  {
    id: 'minimax/video-01',
    owner: 'minimax',
    name: 'MiniMax Video 01',
    description: 'MiniMax production, 720p HD',
    runs: 608100,
    quality: 'Excellent',
    speed: 'Medium (1 min)',
    cost: '$0.10/video',
  },
  {
    id: 'wan-video/wan-2.5-i2v',
    owner: 'wan-video',
    name: 'Wan 2.5 I2V',
    description: 'Alibaba, supports background audio',
    runs: 46800,
    quality: 'Excellent',
    speed: 'Medium',
    cost: '~$0.08/video',
  },
  {
    id: 'google/veo-3.1',
    owner: 'google',
    name: 'Veo 3.1',
    description: 'Google latest, supports audio',
    runs: 37700,
    quality: 'Highest',
    speed: 'Slow',
    cost: '~$0.30/video',
  },
  {
    id: 'minimax/hailuo-02',
    owner: 'minimax',
    name: 'Hailuo 02',
    description: 'MiniMax Hailuo model',
    runs: 189800,
    quality: 'Excellent',
    speed: 'Medium',
    cost: '~$0.12/video',
  },
  {
    id: 'google/veo-3',
    owner: 'google',
    name: 'Veo 3',
    description: 'Google Veo previous generation',
    runs: 194300,
    quality: 'Highest',
    speed: 'Slow',
    cost: '~$0.25/video',
  },
  {
    id: 'lightricks/ltx-video',
    owner: 'lightricks',
    name: 'LTX Video',
    description: 'Ultra-fast generation, 10s completion',
    runs: 160900,
    quality: 'Excellent',
    speed: 'Ultra-fast (10s)',
    cost: '$0.015/video',
  },
  {
    id: 'stability-ai/stable-video-diffusion:3f0457e4619daac51203dedb472816fd4af51f3149fa7a9e0b5ffcf1b8172438',
    owner: 'stability-ai',
    name: 'Stable Video Diffusion',
    description: 'Classic stable, 3-4s video',
    runs: 5000000,
    quality: 'Good',
    speed: 'Fast (30s)',
    cost: '$0.018/video',
  },
];
